set-option -g prefix C-a
set -g default-terminal "screen-256color"

# Enable mouse
set -g mouse on

# Disable rename window
set-option -g allow-rename off

# Atalho para última window
bind-key L last-window

# Start numbering at 1
set -g base-index 1

set -s escape-time 0
setw -g aggressive-resize on
# Scroll history
set -g history-limit 300000

# Move around panes vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload tmux config
bind r source-file ~/.tmux.conf

# THEME
set -g status-bg black
set -g status-fg white
set -g status-left ""
set -g status-right "#[fg=green]#H"
set-window-option -g window-status-current-bg red
