-- local Worktree = require "git-worktree"
-- local utils = require "rds.utils"
--
-- local create_git_worktree = function()
--   local branch = utils.input "Branch name: "
--   Worktree.create_worktree(branch, branch, "origin")
-- end
--
-- local group = vim.api.nvim_create_augroup("git", { clear = true })
--
-- vim.api.nvim_create_autocmd("BufEnter", {
--   group = group,
--   desc = "Autocmd to block code changes on main branch (because I always forget this xD)",
--   -- TODO: better matching for files?
--   pattern = "*.*",
--   -- buffer = 0,
--   callback = function()
--     local branch = vim.fn.FugitiveHead()
--     local block_main_flag = vim.env["BLOCK_MAIN"]
--
--     if branch == "main" and block_main_flag == "1" then
--       print "Main branch blocked"
--       local bufnr = vim.api.nvim_get_current_buf()
--       vim.api.nvim_set_option_value("modifiable", false, { buf = bufnr })
--     end
--   end,
-- })
--
-- vim.keymap.set("n", "<Leader>gg", "<Cmd>G<CR>")
-- vim.keymap.set("n", "<Leader>gp", "<Cmd>G pull<CR>")
-- vim.keymap.set("n", "<Leader>gP", "<Cmd>G push<CR>")
--
-- -- Git worktree extension
-- -- TODO: do I really want to use worktrees or git stash?
-- -- I will try git stash (when needed) for now to simplify my workflow
-- -- vim.keymap.set("n", "<Leader>gl", "<Cmd>lua require('telescope').extensions.git_worktree.git_worktrees()<CR>")
-- -- vim.keymap.set("n", "<Leader>ga", "<Cmd>lua require('telescope').extensions.git_worktree.create_git_worktree()<CR>")
-- -- vim.keymap.set("n", "<Leader>gn", create_git_worktree)
-- vim.keymap.set("n", "<Leader>gl", "<Cmd>lua require('telescope.builtin').git_branches()<CR>")
-- -- vim.keymap.set("n", "<Leader>ga", "<Cmd>lua require('telescope').extensions.git_worktree.create_git_worktree()<CR>")
-- -- vim.keymap.set("n", "<Leader>gn", create_git_worktree)
