- name: Create personal dir
  file:
    path: ~/personal
    state: directory
  tags:
    - core

- name: Create work dir
  file:
    path: ~/work
    state: directory
  tags:
    - core

- name: Install Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - core

- name: Add homebrew to PATH and source
  shell: hehe
  tags:
    - core

- name: Brew tap nerd-fonts
  shell: brew tap homebrew/cask-fonts
  tags:
    - core

- name: Install JetBrains Fonts
  homebrew_cask:
    name: font-jetbrains-mono-nerd-font
    state: latest
  tags:
    - core
