- name: Clone dotfiles repo
  git:
    repo: https://github.com/s-rafaeldias/dotfiles
    dest: ~/.dotfiles
  tags:
    - dotfile

- name: Setup dotfiles
  shell:
    cmd: make stow
    chdir: ~/.dotfiles/
  tags:
    - dotfile

- name: Install brew deps
  shell: brew bundle --file=$HOME/.dotfiles/Brewfile
  tags:
    - dotfiles
