""" Capotes Vimrc
""" Arquivo de configurações do VIM
""" Sections:
""" 00 - Vundle
""" 01 - Colors
""" 02 - Spaces & Tabs
""" 03 - UI Layout
""" 04 - Custom Mappings
""" 05 - Leader Shortcus
""" 06 - Fn Shortcus
""" 07 - Powerline
""" 08 - NERDTree
""" 09 - YouCompleteMe
""" 10 - AutoGroups
""" 11 - Misc

""" 00 - Vundle
""""" START VUNDLE CONFIG
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

""" Utility
Plugin 'tpope/vim-fugitive'
Plugin 'wincent/command-t'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'editorconfig/editorconfig-vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'Valloric/YouCompleteMe'
Plugin 'majutsushi/tagbar'

""" C++
Plugin 'octol/vim-cpp-enhanced-highlight'

""" Python
Plugin 'cjrh/vim-conda'
Plugin 'davidhalter/jedi-vim'

""" Ruby/Rails
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rbenv'

""" Go
Plugin 'fatih/vim-go'
Plugin 'mdempsky/gocode', {'rtp': 'vim/'}

""" NerdTree
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

""" YAML
Plugin 'avakhov/vim-yaml'

""" UI Interface
Plugin 'AnsiEsc.vim'
Plugin 'Lokaltog/powerline'
Plugin 'ryanoasis/vim-devicons'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'jszakmeister/vim-togglecursor'

""" Themes
Plugin 'sonph/onehalf', {'rtp': 'vim/'}
Plugin 'jacoborus/tender.vim'


" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype on
filetype plugin on
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line


""" 01 - Colors
syntax on	" Syntax highlighting
syntax enable	" Enable syntax highlighting
set background=dark
set t_Co=256
colorscheme tender

""" 02 - Spaces & Tabs
set listchars=eol:¬,tab:>-,trail:~,extends:>,precedes:<,space:·
set list

""" 03 - UI Layout
set rnu 	" show relative numbers
set nu 		" show line numbers
set cursorline					" show a visual line under the cursor's current line
set showmatch					" show the matching part of the pair for [] {} and ()
let g:togglecursor_insert='blinking_line'

set colorcolumn=110
highlight ColorColumn ctermbg=darkgray

""" 04 - Custom Mappings
" Disable arrow keys
noremap  <Up> ""
noremap! <Up> <Esc>
noremap  <Down> ""
noremap! <Down> <Esc>
noremap  <Left> ""
noremap! <Left> <Esc>
noremap  <Right> ""
noremap! <Right> <Esc>

" Move line up
nnoremap - ddp
" Move line down
nnoremap _ ddkP
" Upper word on insert mode
inoremap <c-u> <esc>bveUea
" Upper word on normal mode
nnoremap <c-u> bveUe
" Remap jk for exit Insert mode
inoremap kj <Esc>
inoremap <Esc> <nop>

""" 05 - Leader Shortcus
let mapleader=","
" Open vim config
nnoremap <leader>ev :vsplit $MYVIMRC<CR>
" Reload vim config
nnoremap <leader>sv :source $MYVIMRC<CR>
" Wrap word in double quotes
nnoremap <Leader>" viw<esc>a"<esc>bi"<esc>lel
" Wrap word in single quotes
nnoremap <Leader>' viw<esc>a'<esc>bi'<esc>lel
" Wrap selected area in Visual mode in single quotes
vnoremap <Leader>' <Esc>`>a'<Esc>`<i'<Esc>
" Wrap selected area in Visual mode in double quotes
vnoremap <Leader>" <Esc>`>a"<Esc>`<i"<Esc>


""" 06 - Fn Shortcus
set pastetoggle=<F2>
nmap <F8> :TagbarToggle<CR>

""" 07 - Powerline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='tender'
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'

""" 08 - NERDTree
let NERDTreeQuitOnOpen = 1
let NERDTreeShowHidden=1
let NERDTreeChDirMode=2
map <c-d> :NERDTreeToggle<CR>

""" 09 - YouCompleteMe
let g:ycm_filetype_blacklist = { 'python': 1, 'ruby': 1 }

""" 10 - AutoGroups
" disable continuation of comments to the next line
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro
" Ruby settings
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
" Python settings
autocmd FileType python iabbrev <buffer> iff if:<left>i

augroup code_comment
    autocmd FileType python,yaml  nnoremap <buffer> <Leader>c I#<esc>
    autocmd FileType javascript   nnoremap <buffer> <Leader>c I//<esc>
augroup END


""" 11 - Misc
"set nocompatible
set encoding=utf8

" Disable annoying beeping
set noerrorbells
set vb t_vb=

set timeoutlen=1000 ttimeoutlen=0

set tags=./tags

if $PATH !~ "/.rbenv"
    let $PATH="/home/rafael/.rbenv/shims:/home/rafael/.rbenv/bin:" . $PATH
endif

set completeopt-=preview

""" Abbreviations
" Fix
inoremap [3~ <Del>
inoremap OQ <F2>
