set-option -g default-shell /usr/bin/zsh
set -s default-terminal tmux-256color
set -as terminal-overrides ",*:Tc"

set-option -g prefix C-a
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
# Enable mouse
set -g mouse on

# Disable rename window
set-option -g allow-rename off

# Atalho para última window
bind-key L last-window

# Start numbering at 1
set -g base-index 1

set -s escape-time 0
setw -g aggressive-resize on
# Scroll history
set -g history-limit 300000

# Move around panes vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload tmux config
bind r source-file ~/.tmux.conf

# THEME
set -g status-bg blue
set -g status-fg white
set -g status-left ""
set -g status-right "#[fg=white]#H"
set-window-option -g window-status-current-bg red
