set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "jlipps/tmux-safekill"

# Reload the file with prefix r
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# set-option -sa terminal-overrides 'screen-256color:RGB'

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Don't rename windows
set-option -g allow-rename off

# Make splitting windows easier
# bind-key v split-window -h
# bind-key s split-window -v

# Moving between panes
bind j select-pane -L
bind \; select-pane -R
bind l select-pane -U
bind k select-pane -D

# Quick pane selection
# bind -r C-h select-window -t :-
# bind -r C-l select-window -t :+

# Pane resizing
bind -r J resize-pane -L 5
bind -r L resize-pane -U 5
bind -r K resize-pane -D 5
bind-key - select-layout even-vertical
bind-key | select-layout even-horizontal

set-window-option -g mode-keys vi

# # Update default binding of `Enter` to also use copy-pipe
# unbind -Tcopy-mode-vi Enter
# bind-key -Tcopy-mode-vi Enter send -X copy-pipe-and-cancel pbcopy

# Use prefix C-l to clear the visible scrollback lines
# bind C-l send-keys 'C-l'

# # Use prefix C-k to clear the scrolled off (hidden) buffer lines
# bind C-k clear-history

# Break pane out into new window
bind-key b break-pane -d

# Quickly switch between sessions
bind-key C-j choose-tree

# Quickly view system & process info in htop
bind-key g split-window -h -p 35 "gotop"

# Break out new session based on current pane
# bind-key C-b send-keys 'tat && exit' 'C-m'

# Open gitsh in 31% pane
# bind g split-window -h -p 30 'gitsh'

# # Open 30% terminal pane
# bind j split-window -h -p 30

# }}}

# Settings {{{

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Setting the delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Tells tmux up front what shell to expect
set-option -g default-shell /usr/local/bin/fish

# Toggle mouse on and off with prefix-m
bind m \
  set-option -g mouse on \;\
  display 'Mouse: ON'

# Toggle mouse off with prefix-M
bind M \
  set-option -g mouse off \;\
  display 'Mouse: OFF'

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Remove delay when pressing esc in Vim
set -sg escape-time 0

# Extend display time of status messages to 2 seconds
set-option -g display-time 2000

# Display tmux session name in terminal title (instead of just "tmux")
set-option -g set-titles on

# Increase scrollback lines (default is 2000)
set-option -g history-limit 5000

# set the color of the window list
setw -g window-status-style fg=black,bg=colour12

# set colors for the active window
setw -g window-status-current-style fg=white,bg=red,bright

# pane colors
set -g pane-border-style bg=default,fg=default
set -g pane-active-border-style bg=default,fg=blue

set -g message-style fg=white,bg=black

# Enable UTF-8 support in status bar
set -g status on

# set the status line's colors
# set -g status-fg default
set -g status-style bg=black

# Status bar settings
set -g status-left-length 60
set -g status-left "#[fg=green][#S] #[fg=red]w#I #[fg=blue]p#P"
set -g status-right-length 60
set -g status-right " #[fg=white]%a, %b %d | %H:%M "
set -g status-interval 15 # default is 15
set -g status-justify centre

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
