# Show hidden files? You can toggle this by typing 'zh'
set show_hidden true

# Be aware of version control systems and display information.
set vcs_aware true

# State of the four backends git, hg, bzr, svn. The possible states are
# disabled, local (only show local info), enabled (show local and remote
# information).
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled
set vcs_backend_svn disabled

# Show dotfiles in the bookmark preview box?
set show_hidden_bookmarks true

