require "rds.autocmd"
--
-- require "rds.utils"
require "rds.treesitter"
require "rds.snippets"
require "rds.cmp"
-- TODO: better way to do this?
require "rds.lsp"
-- require "rds.lsp.python"
-- require "rds.lsp.lua"
-- require "rds.lsp.arduino"
-- require "rds.lsp.scala"

require "rds.telescope"
require "rds.statusline"
require "rds.git"
require "rds.harpoon"
require "rds.notes"
-- require "rds.worktree"
require "rds.dap"
