-- require("orgmode").setup_ts_grammar()
--
-- require("orgmode").setup {
--   org_agenda_files = { "~/workspace/org/*" },
--   org_default_notes_file = "~/workspace/org/refile.org",
--   org_indent_mode = "noindent",
--   org_agenda_skip_scheduled_if_done = true,
--   org_agenda_skip_deadline_if_done = true,
--   org_todo_keywords = { "WAITING(w)", "TODO(t)", "DOING(D)", "|", "DONE(d)", "CANCELED" },
--   org_agenda_start_on_weekday = 7,
--   -- org_agenda_templates = {
--   -- t = {
--   -- description = "Task",
--   -- template = "* TODO %?\n   %u\n",
--   -- },
--   -- },
--   mappings = {
--     org = {
--       org_toggle_checkbox = "<Leader>t",
--     },
--   },
-- }
--
-- require("org-bullets").setup {
--   symbols = { "◉", "○", "✸", "✿" },
-- }
